### ISSUE TITLE
Add Support Elasticsearch 5.x

### ISSUE THREAD

**Issue by civovic** [rhblind/drf-haystack#131]
I see Pipfile using elasticsearch = "<3.0.0,>=2.0.0"

I have a problem when using elasticsearch 5.x with docker? because elastic 2.4.1 docker isn't avalaible
Is it possible update that elastic python library using elasticsearch>=5.0.0,<6.0.0 ?

thank you in advance

**Comment by rhblind** [comment]
Have to wait for new release of django-haystack before adding support for ES5. I see they have support in their master branch, but no released version yet.

**Comment by piedrahitapablo** [comment]
Haystack now supports elasticsearch 5.x.x, can drf-haystack be used with the new version of haystack? or there any other issues aside from the pipfile? in advance

**Comment by Afnarel** [comment]
Now, django-haystack supports ElasticSearch 7.x.x in its versions >=3.2: https://github.com/django-haystack/django-haystack/blob/v3.2.1/setup.py#L61

I [saw here](https://github.com/rhblind/drf-haystack/issues/146) that @rhblind is trying to pass it on to someone else (@decibyte ou JazzBand?). What is the exact status? Can we expect a support for django-haystack >=3.2 (and therefore ElasticSearch >=7)?

My problem is I would like to move to drf-haystack but I have django-elasticsearch-dsl and elasticsearch-dsl installed and they require at least elasticsearch >=6, so there is a conflict between the two.

Thanks for the work on this package by the way!

**Comment by mka142** [comment]
I am using ElasticSearch 7.17.0 and i'ts working fine. You just need to install drf-haystack from source `pip install -e git+https://github.com/rhblind/drf-haystack.git#egg=drf-haystack`. Support for django-haystackk <=3.2 was added by #164, but there was no any new release since then.

**Comment by Afnarel** [comment]
Ah yes indeed it is supported on the master branch. Unfortunately I'm not sure I will be able to install it without a specific release since the project I'm working on has a strict policy of fixing versions of packages. Thank you for your help in any case :)

Maybe this issue is not the best place to discuss this, but I checked the documentation and didn't see anything about a release cycle. Do you know if there are specific rules in place for this project, or if a new release is planned anytime soon?

**Comment by mka142** [comment]
Sorry, I don't know. It's rather question for the author.
- [ ] I think that you can also omit your policy by publishing your own version of drf-haystack from master brach on pypi. Of course it't not the point, but for now I don't see any other possibilities.

**Comment by decibyte** [comment]
I believe this issue is resolved. Feel free to reopen with an explanation of what is missing, if you think I am wrong.
