### ISSUE TITLE
Django 3.0 - no module named six

### ISSUE THREAD

**Issue by aleksanb** [rhblind/drf-haystack#148]
If we wish to support django 3.0 we'll have to change the current imports from six, as it's no longer reexported from django itself.

**Comment by decibyte** [comment]
@aleksanb, would you be able to provide a pull request for this? Then I'd be happy to review it. It seems like a somewhat trivial task, but I'm afraid it's not going to be done soon anyway, unless someone who actually needs it right now will do the work :)

**Comment by aleksanb** [comment]
We ended up integrating directly against elasticsearch as part of a larger search-rewrite on our end.
Thanks for having made the project though, we did use it for years! :)
