### ISSUE TITLE
 Cannot install with Django 3 compatible version of Haystack

### ISSUE THREAD

**Issue by Gulci** [rhblind/drf-haystack#152]
Currently the only version of django-haystack that supports Django 3 is a pre-release, v3.0b2.

It is currently impossible to install drf-haystack if you are using Django 3 and this pre-release of django-haystack because of drf-haystack's dependency requirements (`"django-haystack>=2.8,<2.9"`).

**Comment by rhblind** [comment]
Fixed in master branch
