### ISSUE TITLE
Highlighting fails with TypeError when highlighter_field value is None (while using HighlighterMixin)

### ISSUE THREAD

**Issue by ajiteshr7** [rhblind/drf-haystack#155]
## Expected behavior
Should return a empty string instead.
## Actual behavior
Argument of type 'NoneType' is not iterable

```
ret["highlighted"] = highlighter.highlight(getattr(instance, self.highlighter_field or document_field))
 
def highlight(self, text_block):
        self.text_block = strip_tags(text_block)
```
## Steps to reproduce the behavior

1. Index a field with null value and try using HighlighterMixin to get the highlighted field.

While using `drf-haystack==1.7.1rc2` but master seems to have the same implementation.

## Insights

This can be fixed by:

`ret["highlighted"] = highlighter.highlight(getattr(instance, self.highlighter_field or document_field) or '')`

**Comment by rhblind** [comment]
Hello, thanks for the report.
Would you consider creating a PR for this? 🙂

**Comment by ajiteshr7** [comment]
@rhblind  Yeah, will do. Given me few days to raises PR.
