### ISSUE TITLE
Please upgrade django version 

### ISSUE THREAD

**Issue by 13KuntalRoy** [rhblind/drf-haystack#178]

**Comment by SimonielMusyoki** [comment]
Please update to support Django 4, its conflicting and I have to downgrade my Django to version 3

**Comment by decibyte** [comment]
@13KuntalRoy I see that [you pushed changes to include Django 4](https://github.com/rhblind/drf-haystack/commit/78287cc8d8289676826becc207370f0e4f2e8dfe). Did you also check that things actually work? Are tests passing?

**Comment by jock-tanner** [comment]
I didn't run tests (I couldn't find any guidance in your docs, and I'm not familiar with Tox), but it works for me (Django 4.1), and I'd like to give this issue a +1.

**Comment by mattonit** [comment]
will you push the new version to PyPI?
