### ISSUE TITLE
Is this project still supported?

### ISSUE THREAD

**Issue by whitewhite944** [rhblind/drf-haystack#194]
Description

Is this project still maintained? this project has not released a stable version for more than a year. Would like to know if this is something that is still appropriate for new projects????thank you

**Comment by rhblind** [comment]
Hi, unfortunately I can’t say it really is. I’ve tried to ask for new maintainers on multiple occasions, because I don’t really have the time.
I know that many people are using this library, and it would’ve been great if someone could take it from

**Comment by McRo** [comment]
We use it !  Don't have the development skill to maintain this repo, please don't stop develop updates.

**Comment by furlongm** [comment]
Could we get a release with the current commits? That would greatly help as many are stuck on the last released version on pypi

**Comment by decibyte** [comment]
I just realised that I have permissions to make releases on PyPI. I might try giving it a shot soon.

**Comment by rhblind** [comment]
Thank you very much, Mikkel ❤️

**Comment by decibyte** [comment]
I am closing this. Feel free to reopen in case you still consider the issue unresolved.
