### ISSUE TITLE
Loosen version requirements

### ISSUE THREAD

**Issue by jgadelange** [rhblind/drf-haystack#204]
I want to use this package with the (unreleased) [django-haystack v3.3b1](https://github.com/django-haystack/django-haystack/releases/tag/v3.3b1). But since it is really restrictive pip won't let me.

Is it possible to loosen the version requirements so this is possible?

**Comment by decibyte** [comment]
If you're surfing the waves of cutting edge anyway, I suggest you fork this repo, make the changes you need in your own fork, and `pip install` from there instead.

Bonus points if you make a pull request with the changes if it turns out to work well :)

**Comment by jgadelange** [comment]
I would do something along the lines of removing upper limit on the [version of the related packages](https://github.com/rhblind/drf-haystack/blob/master/setup.py#L37-L39) (also prevents needing new releases is another package releases) and make that a problem that is solved by the docs. 

Would that be something you would be open to?

**Comment by decibyte** [comment]
I personally think it's better to keep the upper versions and only bump them after someone has tested that it all actually works together.

I understand that there's a maintenance burden in doing it this way. But the other way, it's removing the very rudimentary QA that comes with stricter compatibility limits. My fear is that loosening up might result in other issues being reported, because someone thought this package is compatible with newer versions of dependencies that we didn't even do a basic check with.

**Comment by decibyte** [comment]
So: If you have the time to verify that this works with newer versions of DJango, DRF and `django-haystack`, a pull request bumping the upper bounds are very much appreciated :)

**Comment by jgadelange** [comment]
I understand your considerations and they are valid. My experience with packages with suboptimal maintenance in the past has lead me to not adding the dependencies to the setup.py and let it purely be a documentation thing. (Your way is the more superior way as long as the package is maintained though ;) )

I do want to point out that in this case `django-haystack@3.2.1` claims not to be compatible with `django@4.2.x`. That is something added in https://github.com/django-haystack/django-haystack/pull/1931/files. So currently `drf-haystack` isn't really compatible with `django@4.2.x`. (though as far as I can see, for 4.2 no fixes were necessary and it should work probably). 

For now I've got it fixed for my situation. Hopefully `django-haystack` gets the situation with their pypi releases sorted out soon so we can have an official release and update the version in the setup.py.

I'll close this issue for now.

**Comment by decibyte** [comment]
Sounds like you're following the situation closely. Again, a PR when everything is sorted out is very welcome. I'd be happy to expedite it and make a new release here.
