### ISSUE TITLE
Number of facets returned on elasticsearch are limited to 10 

### ISSUE THREAD

**Issue by mrk4148-kreios** [rhblind/drf-haystack#206]
Hello everyone. I have facet with following problem: the number of facets returned on elasticsearch are limited to 10, is it possible to increase this number?

As i can see, the number was increased to 100 in this issue https://github.com/django-haystack/django-haystack/issues/658
But it's still 10 for me

receiving facets by - queryset.facet_counts()

Operating system version: Mac os (but dockerized on linux)
Search engine version:
Python version: python:3.11
Django version: Django==4.0.8 djangorestframework==3.12.4
Haystack version: drf-haystack==1.8.13

**Comment by decibyte** [comment]
Hi @mrk4148-kreios

I just did a very brief search in the code base for an obvious thing to update, but didn't fint any.

I wouldn't count on this being fixed, unless you take the time to investigate the matter further and provide a pull request yourself.

**Comment by mrk4148-kreios** [comment]
@decibyte Thank you for response
