### ISSUE TITLE
DRF 3.15 is not supported

### ISSUE THREAD

**Issue by MattJHD** [rhblind/drf-haystack#212]
Master contain:
"djangorestframework>=3.7,<3.16",

but last tag limits version 3.14 of DRF

**Comment by lanterno** [comment]
Any update here?

**Comment by fronbasal** [comment]
Unfortunately still seeing this issue.. any updates from the maintainers?

**Comment by decibyte** [comment]
I have just uploaded [version 1.9](https://pypi.org/project/drf-haystack/1.9/) to PyPI.

**Comment by lanterno** [comment]
@decibyte That's great! thanks a lot!
