### ISSUE TITLE
FilterQueryBuilder combines terms with hard-coded or_ operator

### ISSUE THREAD

**Issue by chriseldredge** [rhblind/drf-haystack#92]
[FilterQueryBuilder.build_query](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/query.py#L89) has been extended to use `self.default_operator` for combining queries, but on [line 134](https://github.com/inonit/drf-haystack/blob/master/drf_haystack/query.py#L134) individual term queries get combined with a hard-coded `operator.or_`.

This makes it difficult or impossible for applications to translate a query string like `?tags=travel&tags=dining` into a backend query like `tags:("travel" AND "dining")`.

How can applications use drf-haystack to execute boolean AND queries on multi-valued fields?

**Comment by rhblind** [comment]
Hi, seems like you've spottet a little bug.
I guess the statement on line 134 should respect the operator defined in the `__init()__` method. A PR is most welcome =)

**Comment by jgadelange** [comment]
Ah, I came across the same bug. I will try to create a PR for it. 
However I was wondering. Should this use the same `default_operator` or should there be an (optional) `default_same_field_operator`?  (I am going to make the PR for the second option)

This also fiels like something you want to be able to easily configure per field. Someone have a good idea on how to accomplish that? I don't see a good hook for that in the current structure, but maybe I miss something 🤔
